### ISSUE TITLE
WatchAll is missing for some resources

### ISSUE THREAD

**Issue by cortex93** [tintoy/dotnet-kube-client#134]
Is it normal that WatchAll is not defined on client for all ressources like Secret ?

**Comment by tintoy** [comment]
Hi - sorry, work’s been a little crazy. I’ll take a look at this first thing tomorrow morning :)

**Comment by tintoy** [comment]
Hi.

It's not a deliberate decision, just that nobody has needed it yet. It's pretty easy to add. I'll do so shortly for `SecretV1` so you can see what's involved.

PS.

**Comment by tintoy** [comment]
Hi - apologies for the delay; I've added WatchAll for both Secrets and ConfigMaps.

Published new packages ([v2.3.15](https://travis-ci.org/github/tintoy/dotnet-kube-client/builds/765697322)).

BTW, not _all_ resource types support WatchAll, but most do. If you look in `src/Swagger/kube-swagger.yml`, you'll see all supported actions for a given resource type .

For example, for `v1/Pod`, look for the following YAML:

```yml
x-kubernetes-action: list
  x-kubernetes-group-version-kind:
    group: ''
    kind: ConfigMap
    version: v1
```

For Watch, you want `x-kubernetes-action: get`, and for WatchAll, you want `x-kubernetes-action: list`. In both cases, the request must have:

```yaml
parameters:
  in: query
  name: watch
```
