### ISSUE TITLE
Serialization sets invalid default values

### ISSUE THREAD

**Issue by bastianeicher** [tintoy/dotnet-kube-client#36]
Assume the following deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test
          image: nginx
```
Creating this with `kubectl apply` succeeds.

Trying to do the same with KubeClient fails with an "unprocessable entity" error:
```csharp
var deployment = new DeploymentV1Beta1
{
    Metadata = new ObjectMetaV1 {Name = "test"},
    Spec = new DeploymentSpecV1Beta1
    {
        Selector = new LabelSelectorV1
        {
            MatchLabels = {["app"] = "test"}
        },
        Template = new PodTemplateSpecV1
        {
            Metadata = new ObjectMetaV1
            {
                Labels = {["app"] = "test"}
            },
            Spec = new PodSpecV1
            {
                Containers =
                {
                    new ContainerV1
                    {
                        Name = "test",
                        Image = "nginx"
                    }
                }
            }
        }
    }
}));
client.Create(deployment);
```

Serializing the deployment object to JSON with `JsonConvert.SerializeObject(deployment)` and then converting it to YAML for better readability gives the following (slightly abbreviated):
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  uid: 
  clusterName: 
  generateName: 
  # ...
spec:
  paused: false
  selector:
    matchExpressions: []
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
      uid: 
      clusterName: 
      generateName: 
      name: 
      # ...
    spec:
      hostIPC: false
      hostPID: false
      hostname: 
      nodeName: 
      # ...
      containers:
      - name: test
        image: nginx
        command: []
        lifecycle: 
        livenessProbe:        
        readinessProbe: 
        # ...
      hostAliases: []
      imagePullSecrets: []
      initContainers: []
      readinessGates: []
      # ...
  rollbackTo: 
  minReadySeconds: 0
  progressDeadlineSeconds: 0
  replicas: 0
  revisionHistoryLimit: 0
  strategy: 
status: 
```

Trying this with `kubectl apply` fails with: `unknown field "readinessGates" in io.k8s.api.core.v1.PodSpec`
After removing that field it fails with: `spec.progressDeadlineSeconds: Invalid value: 0: must be greater than minReadySeconds.`

I suppose the underlying problem is, that fields like `DeploymentV1.ProgressDeadlineSeconds` have documentation like `Defaults to 600s.` but these default values are not represented in code and the fields in question are not nullable.
