### ISSUE TITLE
Can't create a service

### ISSUE THREAD

**Issue by MichaelJCompton** [tintoy/dotnet-kube-client#68]
The `TargetPort` of a service is set as a string https://github.com/tintoy/dotnet-kube-client/blob/master/src/KubeClient/Models/generated/ServicePortV1.cs#L46, which fails when trying to create a service.  

Exception message : "Unable to create v1/Service resource in namespace '...'.\nInvalid: Service \"my-service\" is invalid: spec.ports[0].targetPort: Invalid value: \"9376\": must contain at least one letter or number (a-z, 0-9)"

I think it needs different serialisation depending if it's an integer or string value: e.g. https://github.com/kubernetes-client/csharp/blob/master/src/KubernetesClient/generated/Models/V1ServicePort.cs#L113 and https://github.com/kubernetes-client/csharp/blob/master/src/KubernetesClient/IntstrIntOrString.cs#L6-L19

**Comment by tintoy** [comment]
Ouch, yes I see why that could be an issue. I might try for a custom converter for the YAML... Out of curiosity, what happens if you forcibly quote the port, rather than leaving it as a number?

**Comment by MichaelJCompton** [comment]
Na, looks like it's got to arrive server-side serialised as a number.  e.g. if I just try to `kubectl apply ...` this

```
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: MyApp
  ports:
  - protocol: TCP
    port: 80
    targetPort: "9376"
```

I get the same error from kubernetes : "The Service "my-service" is invalid: spec.ports[0].targetPort: Invalid value: "9376": must contain at least one letter or number (a-z, 0-9)"
