### ISSUE TITLE
Working with custom objects from CRDs

### ISSUE THREAD

**Issue by stephenpope** [tintoy/dotnet-kube-client#76]
I wondered if you could guide me to an example .. I am now starting to create my own resources (CRDs) in K8S ..
For example - `/apis/things.example.com/v1/namespaces/default/things`
```yaml
apiVersion: "things.example.com"
kind: MyThing
metadata:
    name: my-first-thing
spec:
    thingState: draft
    thingSizes:
        - xl
        - xxl
```
I was wondering what the best way to handle CRDs in `dotnet-kube-client` and to have it retrieve (and if possible) deserialise to a C# object that represents `MyThing`. 

I like the way you have put the library together and I would like to move to this, so I am just evaluating how to do certain things (I appreciate this is a relatively new feature of K8S)

In the official K8S CSharp client the closest I can get is `GetNamespacedCustomObject` that just returns me an `object` .. which isnt terribly helpful :)
